import logging
from unittest.mock import Mock, patch

from dollar_dashboard import __version__
from dollar_dashboard.run_history import APP_VERSION, SCHEMA_VERSION
from dollar_dashboard.official_policy import _pdf_text


def test_v342_metadata_schema_unchanged():
    assert tuple(map(int, __version__.split("."))) >= (3,4,2)
    assert tuple(map(int, APP_VERSION.split("."))) >= (3,4,2)
    assert SCHEMA_VERSION == "3.4.1"


def test_pdf_rejects_http_200_html_without_calling_pypdf():
    r=Mock()
    r.content=b'<html>temporary CDN page</html>'
    r.url='https://example.test/report.pdf'
    r.headers={'content-type':'text/html'}
    with patch('dollar_dashboard.official_policy._get', return_value=r), \
         patch('dollar_dashboard.official_policy.cached_official_source_text', return_value={'ok':False}):
        out=_pdf_text(r.url,1)
    assert out['ok'] is False
    assert 'non-PDF content' in out['error']


def test_pdf_reader_warning_level_is_restored():
    # Use a tiny valid PDF generated by pypdf itself. The purpose is to verify the
    # targeted logger suppression is scoped to extraction rather than global.
    from io import BytesIO
    from pypdf import PdfWriter
    buf=BytesIO(); w=PdfWriter(); w.add_blank_page(width=72,height=72); w.write(buf)
    r=Mock(); r.content=buf.getvalue(); r.url='https://example.test/report.pdf'; r.headers={'content-type':'application/pdf'}
    lg=logging.getLogger('pypdf._reader'); prior=lg.level; lg.setLevel(logging.WARNING)
    try:
        with patch('dollar_dashboard.official_policy._get', return_value=r), \
             patch('dollar_dashboard.official_policy._cache_put'), \
             patch('dollar_dashboard.official_policy.cached_official_source_text', return_value={'ok':False}):
            out=_pdf_text(r.url,1)
        # Blank page has no text, so extraction is correctly treated as failed, but logger state is restored.
        assert out['ok'] is False
        assert lg.level == logging.WARNING
    finally:
        lg.setLevel(prior)


if __name__ == '__main__':
    test_v342_metadata_schema_unchanged()
    test_pdf_rejects_http_200_html_without_calling_pypdf()
    test_pdf_reader_warning_level_is_restored()
    print('v3.4.2 tests passed')
